services:
  - type: web
    name: smart-crop-advisory-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn smart_crop_advisory.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        sync: false   # You'll paste this manually from Supabase
