# ML models directory — contains training scripts and saved model files
# crop_model.pkl        — trained Random Forest (generated by train_crop_model.py)
# label_encoder.pkl     — LabelEncoder (generated by train_crop_model.py)
# disease_model.pth     — ResNet-18 weights (generated by train_disease_model.py)
# Crop_recommendation.csv  — Kaggle dataset (add manually)
# PlantVillage/            — Kaggle dataset (add manually)
