# Generated by Django 4.2.7 on 2026-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content in soil (kg/ha)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content in soil (kg/ha)')),
                ('potassium', models.FloatField(help_text='Potassium content in soil (kg/ha)')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('humidity', models.FloatField(help_text='Relative humidity (%)')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('ph', models.FloatField(help_text='Soil pH value (0–14)')),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Model confidence (0.0–1.0)')),
                ('weather_advisory', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crop Recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
