# Generated by Django 4.2.7 on 2026-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/diseases/')),
                ('disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField(help_text='Confidence score 0.0–1.0')),
                ('remedy', models.TextField(help_text='Recommended treatment / remedy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disease Detection',
                'ordering': ['-created_at'],
            },
        ),
    ]
