# Generated by Django 4.2.7 on 2026-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetection',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Confidence score 0.0–1.0', null=True),
        ),
        migrations.AlterField(
            model_name='diseasedetection',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diseasedetection',
            name='remedy',
            field=models.TextField(blank=True, help_text='Recommended treatment / remedy', null=True),
        ),
    ]
